import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import {mkdtempSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {IDBFactory} from 'fake-indexeddb';
import {MemoryJournal,IndexedDBJournal} from '../web-sdk/src/storage.mjs';
import {uploadJournal,startJournalDelivery} from '../web-sdk/src/transfer.mjs';
import {createNetworkLogRelay} from '../web-sdk/dev-relay.mjs';
const line=id=>JSON.stringify({event_id:id})+'\n';
const json=body=>new Response(JSON.stringify(body));
const registration={version:2,collector_id:'collector',source_id:'source',handle:'handle'};
function upstream(calls=[]){return async(url,options)=>{calls.push([url,options]);if(url.endsWith('/register'))return json(registration);if(url.endsWith('/presence'))return json({version:2});return json({...registration,acknowledged_event_ids:options.body.trim().split('\n').map(s=>JSON.parse(s).event_id)});};}
async function waitFor(predicate){for(let i=0;i<100;i++){if(await predicate())return;await new Promise(r=>setTimeout(r,5));}throw new Error('Condition did not occur');}
test('memory admission is bounded and canonical',async()=>{const journal=new MemoryJournal({maxEvents:1});assert.equal(journal.append(line('a')),true);assert.equal(journal.append(line('b')),false);assert.equal(journal.exportNDJSON(),line('a'));assert.equal(journal.stats.dropped,1);assert.throws(()=>journal.append('{}\n{}\n'),/complete/);});
test('metadata-first open does not hydrate history; keyset read, identity and cursor survive reopen',async()=>{
 const indexedDB=new IDBFactory(),options={indexedDB,journalId:'journal'};let journal=await IndexedDBJournal.open(options);for(let i=0;i<500;i++)journal.append(line(String(i)));await journal.flush();const identity=journal.identity;await journal.acknowledge('collector','source',400);await journal.close();journal=await IndexedDBJournal.open(options);
 assert.equal(journal._lines.length,0);assert.equal(journal.stats.events,500);assert.equal(journal.identity.environment_id,identity.environment_id);assert.equal(journal.getDeliveryCursor('collector','source'),400);assert.equal(journal.getDeliveryCursor('collector','other'),0);const page=await journal.readPage(498);assert.deepEqual(page.lines,[line('498'),line('499')]);assert.equal(page.next,500);assert.equal((await journal.exportNDJSON()).split('\n').length,501);await journal.close();
});
test('healthy journal owner cannot be displaced',async()=>{const options={indexedDB:new IDBFactory(),journalId:'owned'};const first=await IndexedDBJournal.open(options);await assert.rejects(IndexedDBJournal.open(options),/Another writer/);first.append(line('a'));await first.close();const second=await IndexedDBJournal.open(options);assert.equal(await second.exportNDJSON(),line('a'));await second.close();});
test('expired owner epoch fences late ACK and append after a replacement opens',async()=>{let time=0;const options={indexedDB:new IDBFactory(),journalId:'epoch',locks:null,now:()=>time,leaseMs:1000};const first=await IndexedDBJournal.open(options);first.append(line('a'));await first.flush();time=1001;const second=await IndexedDBJournal.open(options);await assert.rejects(first.acknowledge('collector','source',1),/expired or was replaced/);first.append(line('stale'));await assert.rejects(first.flush(),/expired or was replaced/);await first.close().catch(()=>{});assert.equal(await second.exportNDJSON(),line('a'));await second.close();});
test('pending memory remains bounded across stalled transaction admission',async()=>{const journal=await IndexedDBJournal.open({indexedDB:new IDBFactory(),journalId:'bounded'});journal._queue=new Promise(()=>{});for(let i=0;i<500;i++)assert.equal(journal.append(line(String(i))),true);await Promise.resolve();assert.equal(journal.append(line('overflow')),false);journal._closed=true;clearInterval(journal._renewTimer);journal._db.close();journal._releaseBrowserLock?.();});
test('incremental uploads register zero-event pages and never resend committed prefix',async()=>{const calls=[],journal=new MemoryJournal(),options={origin:'https://app.test',appId:'app',fetchImpl:upstream(calls)};await uploadJournal(journal,options);assert.equal(calls.filter(([url])=>url.endsWith('/events')).length,0);for(let i=0;i<501;i++)journal.append(line(String(i)));const result=await uploadJournal(journal,options);assert.equal(result.events,501);assert.equal(result.batches,2);assert.equal((await uploadJournal(journal,options)).events,0);assert.equal(calls.filter(([url])=>url.endsWith('/events')).length,2);});
test('lost ACK replays same IDs and invalid identity cannot publish cursor',async()=>{const journal=new MemoryJournal();journal.append(line('stable'));const options={origin:'https://app.test',fetchImpl:async(url,opts)=>url.endsWith('/register')?json(registration):json({...registration,source_id:'wrong',acknowledged_event_ids:['stable']})};await assert.rejects(uploadJournal(journal,options),/identity/);assert.equal(journal.getDeliveryCursor('collector','source'),0);await uploadJournal(journal,{...options,fetchImpl:upstream()});assert.equal(journal.getDeliveryCursor('collector','source'),1);});
test('continuous sender wakes for append exactly at drain completion',async()=>{const journal=new MemoryJournal(),calls=[];let appended=false;const fetchImpl=async(url,options)=>{if(url.endsWith('/presence')&&!appended){appended=true;journal.append(line('race'));}return upstream(calls)(url,options);};const sender=startJournalDelivery(journal,{origin:'https://app.test',fetchImpl});await waitFor(()=>journal.getDeliveryCursor('collector','source')===1);sender.stop();assert.equal(calls.filter(([url])=>url.endsWith('/events')).length,1);});
async function relayServer(t,{reachable=false,authorize,fetchImpl=async(url,opts)=>url.endsWith("/register")?json({...registration,source_token:"source-private-secret"}):upstream()(url,opts),manifest=true}={}){
 const directory=mkdtempSync(join(tmpdir(),'relay-v2-')),path=join(directory,'active.json');t.after(()=>rmSync(directory,{recursive:true,force:true}));if(manifest)writeFileSync(path,JSON.stringify({version:2,collector_id:'collector',endpoint:'http://127.0.0.1:4319',enrollment_token:'private-secret-ticket'}),{mode:0o600});
 let relay;const server=http.createServer((req,res)=>relay(req,res));await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>{server.closeAllConnections();server.close();});const origin=reachable?'https://frontend.example':`http://127.0.0.1:${server.address().port}`;relay=createNetworkLogRelay({origin,connectionFile:path,reachable,authorize,fetchImpl});return{path,origin,url:`http://127.0.0.1:${server.address().port}/__network_log`};
}
async function rawFetch(url,options){return new Promise((resolve,reject)=>{const req=http.request(url,{method:options.method,headers:options.headers},res=>{const chunks=[];res.on('data',c=>chunks.push(c));res.on('end',()=>resolve(new Response(Buffer.concat(chunks),{status:res.statusCode})));});req.on('error',reject);req.end(options.body);});}
const body={version:2,platform:'web',registration_id:'journal',journal_id:'journal',installation_id:'installation',environment_id:'environment',instance_id:'page',app_id:'app',environment_name:'Browser'};
test('frontend before collector returns waiting and discovers later private manifest',async t=>{const relay=await relayServer(t,{manifest:false});const options={method:'POST',headers:{Origin:relay.origin,'Content-Type':'application/json'},body:JSON.stringify({...body,origin:relay.origin})};assert.equal((await fetch(relay.url+'/register',options)).status,503);writeFileSync(relay.path,JSON.stringify({version:2,collector_id:'collector',endpoint:'http://127.0.0.1:4319',enrollment_token:'private-secret-ticket'}),{mode:0o600});const config=await(await fetch(relay.url+'/register',options)).json();assert.equal(config.version,2);assert.equal(JSON.stringify(config).includes('secret'),false);});
test('relay rejects foreign origins and keeps source token server-side',async t=>{const calls=[];const relay=await relayServer(t,{fetchImpl:async(url,options)=>{calls.push([url,options]);if(url.endsWith('/register'))return json({...registration,source_token:'source-private-secret'});return upstream()(url,options);}});const options={method:'POST',headers:{Origin:relay.origin,'Content-Type':'application/json'},body:JSON.stringify({...body,origin:relay.origin})};assert.equal((await fetch(relay.url+'/register',{...options,headers:{...options.headers,Origin:'https://evil.example'}})).status,403);const response=await fetch(relay.url+'/register',options);assert.equal(response.status,200);const result=await response.json();assert.ok(result.handle);assert.equal(JSON.stringify(result).includes('source-private'),false);assert.equal(calls[0][1].headers.Authorization,'Bearer private-secret-ticket');});
test('reachable relay rejects spoofed Host/Origin without authenticated session and cross-session handles',async t=>{const relay=await relayServer(t,{reachable:true,authorize:req=>req.headers.authorization==='Bearer session-a'?'a':req.headers.authorization==='Bearer session-b'?'b':null,fetchImpl:async(url,options)=>url.endsWith('/register')?json({...registration,source_token:'source-private-secret'}):upstream()(url,options)});const headers={Host:new URL(relay.origin).host,Origin:relay.origin,'Content-Type':'application/json'},options={method:'POST',headers,body:JSON.stringify({...body,origin:relay.origin})};assert.equal((await rawFetch(relay.url+'/register',options)).status,401);const config=await(await rawFetch(relay.url+'/register',{...options,headers:{...headers,Authorization:'Bearer session-a'}})).json();assert.equal((await rawFetch(relay.url+'/events',{method:'POST',headers:{...headers,Authorization:'Bearer session-b','X-Network-Log-Handle':config.handle,'Content-Type':'application/x-ndjson'},body:line('event')})).status,403);});
test('relay forbids remote HTTP and unauthenticated HTTPS configuration',()=>{assert.throws(()=>createNetworkLogRelay({origin:'http://remote.example',reachable:true}),/HTTPS/);assert.throws(()=>createNetworkLogRelay({origin:'https://remote.example',reachable:true}),/authenticated/);});

test('browser environments share origin identity across app databases while journals/installations remain distinct',async()=>{const indexedDB=new IDBFactory();const a=await IndexedDBJournal.open({indexedDB,databaseName:'app-a',journalId:'a'}),b=await IndexedDBJournal.open({indexedDB,databaseName:'app-b',journalId:'b'});assert.equal(a.identity.environment_id,b.identity.environment_id);assert.notEqual(a.identity.installation_id,b.identity.installation_id);await a.close();await b.close();});

test('oversized memory events fail delivery visibly instead of appearing drained',async()=>{const journal=new MemoryJournal();journal.append(JSON.stringify({event_id:'large',data:'x'.repeat(1024*1024)})+'\n');await assert.rejects(uploadJournal(journal,{origin:'https://app.test',fetchImpl:upstream()}),/batch byte limit/);assert.equal(journal.getDeliveryCursor('collector','source'),0);});
