import React, {useEffect,useMemo,useRef,useState} from 'react';
import Sequence from './Sequence.jsx';
import Comparison from './Comparison.jsx';
import {downloadSVG} from './export-svg.mjs';
import {CollectorClient} from './collector-client.mjs';
import LiveConnection from './LiveConnection.jsx';
import Inspector, {Badge} from './Inspector.jsx';
import {filterSessionItems,IMPORT_LIMITS} from './model.mjs';
import {duration,ownerLabel} from './ui.mjs';
import {sampleOptions,loadSample,loadMalformedSample} from './samples.mjs';
const defaults={search:'',owner:'all',outcome:'any',origins:[],kind:'all',recordingId:null};
function Summary({session}){const s=session.summary;return <span>{s.requests} req · {s.failed_requests} failed · {s.unfinished_requests+s.unknown_outcomes} incomplete · {s.handler_calls} handler calls{s.unfinished_handler_calls?` · ${s.unfinished_handler_calls} unfinished handlers`:""}{s.unknown_handler_outcomes?` · ${s.unknown_handler_outcomes} unknown handler outcomes`:""}{session.incomplete?' · recording incomplete':''}</span>;}
function Segments({label,value,choices,onChange}){return <div role="group" aria-label={label} className="segments">{choices.map(([key,text])=><button key={key} aria-pressed={value===key} onClick={()=>onChange(key)}>{text}</button>)}</div>;}
function App(){
 const [capture,setCapture]=useState(null),[sessionId,setSessionId]=useState(null),[screen,setScreen]=useState('import'),[sample,setSample]=useState('multi-session'),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [filters,setFilters]=useState(defaults),[selectedId,setSelectedId]=useState(null),[inspectorOpen,setInspectorOpen]=useState(false),[history,setHistory]=useState([]),[collapsed,setCollapsed]=useState(new Set()),[expanded,setExpanded]=useState({});
 const [navigatorOpen,setNavigatorOpen]=useState(true),[sheet,setSheet]=useState(null),[mobileSearch,setMobileSearch]=useState(false),[view,setView]=useState('sequence'),[page,setPage]=useState(0),[inspectorWidth,setInspectorWidth]=useState(420);
 const [overlay,setOverlay]=useState(()=>window.matchMedia('(max-width:1099px)').matches);
 const [collection,setCollection]=useState(null);
 const [live,setLive]=useState({state:'idle',count:0}),[pairing,setPairing]=useState([]),[pairingOpen,setPairingOpen]=useState(false);
 const automaticLive=!!document.querySelector('meta[name=network-log-collector][content="1"]');
 const [device,setDevice]=useState(null),[followLatest,setFollowLatest]=useState(true);
 const [sources,setSources]=useState([]),[liveSessions,setLiveSessions]=useState([]),[sourceFilter,setSourceFilter]=useState(null),[moreSessions,setMoreSessions]=useState(null);
 const followLatestRef=useRef(true),latestSessionRef=useRef(null);
 function followNewest(value){if(liveRef.current)liveRef.current.followLatest=value;followLatestRef.current=value;setFollowLatest(value);if(value&&liveRef.current){liveRef.current.select(sourceFilter?{source_id:sourceFilter}:{});return;}if(value&&capture?.sessions.length)changeSession(capture.sessions.at(-1).id,true);}
 const liveRef=useRef(),liveWorkerBusy=useRef(false),pendingLive=useRef(null),liveToken=useRef(null),liveOpened=useRef(false);
 const inspectorRef=useRef(),sequenceRef=useRef();
 const [comparison,setComparison]=useState(null),[collectorEpoch,setCollectorEpoch]=useState(0);
 const comparisonRef=useRef(null),comparisonPending=useRef(null),comparisonTrigger=useRef(null),comparisonFollow=useRef(null);
 const [exportError,setExportError]=useState('');
 function exportDiagram(){setExportError('');try{const result=sequenceRef.current?.exportSVG();if(!result)throw new Error();downloadSVG(result.svg,result.filename);}catch{setExportError('SVG export failed. Try a smaller selection or reload the capture.');}}
 const inputRef=useRef(),workerRef=useRef(),generation=useRef(0),focusBeforeInspector=useRef(null),sheetRef=useRef(null),sheetTrigger=useRef(null),workspaceRef=useRef(null);
 const session=capture?.sessions.find(s=>s.id===sessionId)||capture?.sessions[0];
 const projection=useMemo(()=>session?filterSessionItems(session,filters):null,[session,filters]);
 const all=session?[...session.operations,...session.exchanges]:[],item=all.find(x=>x.id===selectedId);
 const listItems=useMemo(()=>{if(!session||!projection)return [];const visible=[...projection.exchanges,...projection.operations.filter(x=>projection.directIds?.has(x.id))];return visible.filter(x=>!x.ancestorIds.some(id=>collapsed.has(id))).sort((a,b)=>session.recordings.findIndex(r=>r.id===a.recordingId)-session.recordings.findIndex(r=>r.id===b.recordingId)||(a.start?.sequence??a.rawEvents[0]?.sequence)-(b.start?.sequence??b.rawEvents[0]?.sequence));},[session,projection,collapsed]);
 useEffect(()=>{const params=new URLSearchParams(location.hash.slice(1)),token=params.get('collector');if(token){historyReplace();liveToken.current=token;}if(automaticLive||token)startLive(token);return()=>{liveRef.current?.stop();workerRef.current?.terminate();};},[]);
 function historyReplace(){window.history.replaceState(null,'',location.pathname+location.search);}
 function ingestLive(text){if(comparisonRef.current){comparisonPending.current=text;return;}if(!text){++generation.current;workerRef.current?.terminate();liveWorkerBusy.current=false;pendingLive.current=null;setCapture(null);setScreen('import');return;}pendingLive.current=text;if(liveWorkerBusy.current)return;flushLive();}
 function flushLive(){const text=pendingLive.current;if(text===null)return;pendingLive.current=null;liveWorkerBusy.current=true;const current=generation.current;
  const worker=new Worker(new URL('./import-worker.mjs',import.meta.url),{type:'module'});workerRef.current=worker;
  worker.onmessage=({data})=>{worker.terminate();liveWorkerBusy.current=false;if(current!==generation.current)return;if(comparisonRef.current){comparisonPending.current=text;if(pendingLive.current!==null)flushLive();return;}if(data.error)setError(data.error);else{setCapture(data.result);const chosen=liveRef.current?.selection;const newest=chosen?.session_id?JSON.stringify([chosen.session_namespace,chosen.session_id]):data.result.sessions.at(-1)?.id;if(followLatestRef.current&&newest!==latestSessionRef.current){setSelectedId(null);setInspectorOpen(false);setHistory([]);setFilters(defaults);setCollapsed(new Set());}latestSessionRef.current=newest;setSessionId(old=>followLatestRef.current?newest:data.result.sessions.some(s=>s.id===old)?old:newest);if(data.result.sessions.length){liveOpened.current=true;setScreen('workspace');}}if(pendingLive.current!==null)flushLive();};
  worker.onerror=e=>{worker.terminate();liveWorkerBusy.current=false;setError(e.message);};worker.postMessage({id:current,files:[{name:'Live collector capture',text}],limits:{maxFileBytes:64*1024*1024}});
 }
 function startLive(token=liveToken.current){setCollection(null);if(!automaticLive&&!token)return;setPairing([]);setPairingOpen(false);setSources([]);setLiveSessions([]);setSourceFilter(null);setMoreSessions(null);setDevice(null);setCapture(null);setScreen('import');latestSessionRef.current=null;setBusy(false);liveOpened.current=false;liveRef.current?.stop();++generation.current;workerRef.current?.terminate();liveWorkerBusy.current=false;pendingLive.current=null;setError('');setSessionId(null);setSelectedId(null);setInspectorOpen(false);setFilters(defaults);setCollapsed(new Set());const client=new CollectorClient({token,automatic:automaticLive,onSources:value=>{if(liveRef.current===client)setSources(value);},onSessions:(value,next)=>{if(liveRef.current===client){setLiveSessions(value);setMoreSessions(next);}},onCapture:text=>{if(liveRef.current===client)ingestLive(text);},onCollection:status=>{if(liveRef.current===client)setCollection(status);},onStatus:status=>{if(liveRef.current===client)setLive(status);},onPairing:value=>{if(liveRef.current===client)setPairing(value);},onDevice:value=>{if(liveRef.current===client)setDevice(value);},onReset:()=>{if(liveRef.current!==client)return;if(comparisonRef.current){comparisonPending.current='';setCollectorEpoch(v=>v+1);return;}liveOpened.current=false;latestSessionRef.current=null;++generation.current;workerRef.current?.terminate();liveWorkerBusy.current=false;pendingLive.current=null;setCapture(null);setSessionId(null);setSelectedId(null);setInspectorOpen(false);setHistory([]);setFilters(defaults);setCollapsed(new Set());setDevice(null);setPairing([]);setPairingOpen(false);setSources([]);setLiveSessions([]);setSourceFilter(null);setScreen('import');}});client.followLatest=followLatestRef.current;liveRef.current=client;client.run();}
 function stopLive(){++generation.current;workerRef.current?.terminate();liveRef.current?.stop();liveRef.current=null;pendingLive.current=null;liveWorkerBusy.current=false;setPairing([]);setPairingOpen(false);setLive({state:'idle',count:0});}
 async function downloadLive(){try{const blob=await liveRef.current.download(),url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download='capture.ndjson';anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(e.message);}}
 const liveControls=<LiveConnection collection={collection} canCollect={!!liveRef.current?.selection.session_id} onCollect={()=>liveRef.current?.collectRelated()} onCancelCollection={()=>liveRef.current?.cancelCollection().catch(e=>setError(e.message))} followLatest={followLatest} onFollowLatest={followNewest} live={live} available={automaticLive||!!liveToken.current} device={device} pairing={pairing} pairingOpen={pairingOpen} onTogglePairing={async()=>{if(pairingOpen){setPairingOpen(false);setPairing([]);return;}const client=liveRef.current;try{if(await client?.pairing()&&liveRef.current===client)setPairingOpen(true);}catch(e){setError(e.message);}}} onStart={()=>startLive()} onStop={stopLive} onDownload={downloadLive} onError={setError} inert={overlay&&inspectorOpen&&!!item}/>;
 useEffect(()=>{const q=window.matchMedia('(max-width:1099px)');const change=()=>setOverlay(q.matches);q.addEventListener('change',change);return()=>q.removeEventListener('change',change);},[]);
 useEffect(()=>{if(overlay&&inspectorOpen)inspectorRef.current?.querySelector('button')?.focus();},[overlay,inspectorOpen,selectedId]);
 useEffect(()=>{setPage(0);},[filters,sessionId]);
 useEffect(()=>{if(sheet){sheetRef.current?.querySelector('button,input,select')?.focus();}},[sheet]);
 useEffect(()=>{const key=e=>{if(comparisonRef.current)return;if(e.key==='Escape'){if(sheet)closeSheet();else closeInspector();}};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key);},[sheet,inspectorOpen]);
 function openSheet(kind){sheetTrigger.current=document.activeElement;setSheet(kind);}
 function closeSheet(){setSheet(null);requestAnimationFrame(()=>sheetTrigger.current?.isConnected&&sheetTrigger.current.focus());}
 function closeInspector(){setInspectorOpen(false);requestAnimationFrame(()=>focusBeforeInspector.current?.isConnected&&focusBeforeInspector.current.focus());}
 function select(id,options={}){followNewest(false);if(options.open===false){setSelectedId(id);return;}if(id!==selectedId&&selectedId)setHistory(h=>[...h,selectedId]);if(!inspectorOpen)focusBeforeInspector.current=document.activeElement;setSelectedId(id);setInspectorOpen(true);}
 function changeSession(id,following=false){if(!following)followNewest(false);if(liveRef.current&&!following){const [namespace,logicalId]=JSON.parse(id);liveRef.current.select({...(sourceFilter?{source_id:sourceFilter}:{}),session_namespace:namespace,session_id:logicalId});}setSessionId(id);setFilters(defaults);setSelectedId(null);setInspectorOpen(false);setHistory([]);setCollapsed(new Set());closeSheet();setScreen('workspace');}
 function toggleCollapse(id){followNewest(false);setCollapsed(old=>{const next=new Set(old);next.has(id)?next.delete(id):next.add(id);return next;});}
 const setFilter=(key,value)=>{followNewest(false);setFilters(old=>({...old,[key]:value}));};
 async function parse(files){
  stopLive();const current=++generation.current;setBusy(true);setError('');workerRef.current?.terminate();
  const worker=new Worker(new URL('./import-worker.mjs',import.meta.url),{type:'module'});workerRef.current=worker;
  worker.onmessage=({data})=>{if(current!==generation.current)return;setBusy(false);if(data.error)setError(data.error);else{setCapture(data.result);setSessionId(data.result.sessions[0]?.id);setScreen('import');setSelectedId(null);setInspectorOpen(false);setHistory([]);setFilters(defaults);setCollapsed(new Set());}worker.terminate();};
  worker.onerror=e=>{if(current===generation.current){setBusy(false);setError(`Import failed: ${e.message}`);}worker.terminate();};
  worker.postMessage({id:current,files});
 }
 async function readFiles(fileList){const files=[...fileList];if(files.some(f=>f.size>IMPORT_LIMITS.maxFileBytes)||files.reduce((n,f)=>n+f.size,0)>IMPORT_LIMITS.maxTotalBytes){setError('Choose files no larger than 16 MiB each and 64 MiB combined.');return;}try{await parse(await Promise.all(files.map(async f=>({name:f.name,text:await f.text()}))));}catch(e){setBusy(false);setError(e.message);}}
 async function openSample(malformed=false){try{await parse(await (malformed?loadMalformedSample():loadSample(sample)));}catch(e){setError(e.message);}}
 const filterControls=<><label className="search-label"><span className="sr-only">Search paths and component names</span><input type="search" aria-label="Search paths and component names" placeholder="Search paths, methods, components…" value={filters.search} onChange={e=>setFilter('search',e.target.value)}/></label><Segments label="Owner filter" value={filters.owner} choices={[["all","All"],["integrator","App"],["sdk","SDK"],["system","System"],["unknown","Unknown"]]} onChange={v=>setFilter('owner',v)}/><Segments label="Outcome filter" value={filters.outcome} choices={[["any","Any outcome"],["success","Success"],["failed","Failed"],["incomplete","Incomplete"],["cancelled","Cancelled"]]} onChange={v=>setFilter('outcome',v)}/><Segments label="Kind filter" value={filters.kind} choices={[["all","All kinds"],["http","HTTP only"],["local","Local calls only"]]} onChange={v=>setFilter('kind',v)}/><div className="origins"><span>Origins</span>{session?.origins.map(origin=><button key={origin} title={origin} aria-label={`Origin ${origin}`} aria-pressed={filters.origins.includes(origin)} onClick={()=>setFilter('origins',filters.origins.includes(origin)?filters.origins.filter(o=>o!==origin):[...filters.origins,origin])}>{new URL(origin).host}</button>)}</div>{projection?.filtersActive&&<button onClick={()=>setFilters(defaults)}>Clear filters</button>}</>;
 const sourceControls=live.state!=='idle'&&<section className="source-navigation" aria-label="Devices and environments"><h3>Devices and environments</h3><button aria-pressed={!sourceFilter} onClick={()=>{setSourceFilter(null);liveRef.current?.select({});}}>All apps and sessions</button>{[...new Set(sources.map(s=>s.environment_id))].map(environment=><details key={environment} open><summary title={environment}>{sources.find(s=>s.environment_id===environment)?.environment_name||environment}{new Set(sources.filter(s=>s.environment_name===sources.find(item=>item.environment_id===environment)?.environment_name).map(s=>s.environment_id)).size>1&&<small>{environment}</small>}</summary>{[...new Set(sources.filter(s=>s.environment_id===environment).map(s=>s.app_id))].map(app=><details key={app} open><summary>{app}</summary>{sources.filter(s=>s.environment_id===environment&&s.app_id===app).map(source=><button key={source.source_id} aria-pressed={sourceFilter===source.source_id} onClick={()=>{followNewest(false);setSourceFilter(source.source_id);liveRef.current?.select({source_id:source.source_id});}}><strong>{source.status||'Last seen with retained history'}</strong>{sources.filter(s=>s.environment_id===environment&&s.app_id===app).length>1&&<small title={source.source_id}>Installation {source.installation_id?.slice(0,8)||source.source_id.slice(0,8)} · {source.instance_id?.slice(0,8)||source.source_id.slice(-8)}</small>}<small>{source.platform}{source.last_seen?' · '+new Date(source.last_seen).toLocaleTimeString():''}</small>{source.reason&&<small>{source.reason}</small>}</button>)}</details>)}</details>)}<h3>Sessions</h3>{liveSessions.map(s=><button key={JSON.stringify([s.session_namespace,s.session_id])} className="session-row" onClick={()=>changeSession(JSON.stringify([s.session_namespace,s.session_id]))}><strong>{s.name||s.session_id}</strong><small>{s.event_count} events · {s.source_ids?.length||1} source(s)</small></button>)}{moreSessions&&<button onClick={()=>liveRef.current?.moreSessions()}>More sessions</button>}{!sources.length&&<p>Ready and waiting for apps. Start an instrumented debug app.</p>}</section>;
 const sessionControls=<>{sourceControls}{live.state==='idle'&&<h3>Sessions</h3>}{live.state==='idle'&&capture?.sessions.map(s=><button key={s.id} className={`session-row ${session?.id===s.id?'active':''}`} onClick={()=>changeSession(s.id)}><strong>{s.name}</strong><span className="mono">{s.sessionId}</span><Summary session={s}/><small>{s.startedAt??'Start not recorded'} · {s.recordings.length} recording(s)</small></button>)}{session&&session.recordings.length>1&&<><h3>Recording periods</h3><button aria-pressed={!filters.recordingId} onClick={()=>setFilter('recordingId',null)}>All recordings</button>{session.recordings.map((r,i)=><button className="session-row" key={r.id} aria-pressed={filters.recordingId===r.id} onClick={()=>setFilter('recordingId',r.id)}><strong>Recording {i+1} · schema {r.schemaVersion}</strong><span>{r.start?.timestamp??'Start not recorded'} · {r.incomplete?'incomplete':r.end?.data.reason||'ended'}</span></button>)}<p className="muted">File order. Recording clocks are independent; gaps between them are not measured.</p></>}</>;
 function enterComparison(){comparisonTrigger.current=document.activeElement;comparisonFollow.current=liveRef.current?.followLatest;if(liveRef.current)liveRef.current.followLatest=false;const value={capture,session,sourceFilter};comparisonRef.current=value;setComparison(value);}
 function exitComparison(){comparisonRef.current=null;setComparison(null);if(liveRef.current)liveRef.current.followLatest=comparisonFollow.current;const pending=comparisonPending.current;comparisonPending.current=null;if(pending!==null)ingestLive(pending);requestAnimationFrame(()=>{const trigger=comparisonTrigger.current?.isConnected?comparisonTrigger.current:[...document.querySelectorAll('button')].find(button=>button.textContent==='Compare with…'&&button.getClientRects().length);trigger?.focus({preventScroll:true});});}
 const modalOpen=overlay&&inspectorOpen&&!!item;
 function trapTab(e){if(e.key!=='Tab')return;const controls=[...e.currentTarget.querySelectorAll('button,input,select,[tabindex="0"]')].filter(x=>!x.disabled&&x.getClientRects().length);const i=controls.indexOf(document.activeElement);if(e.shiftKey&&i===0){e.preventDefault();controls.at(-1)?.focus();}else if(!e.shiftKey&&i===controls.length-1){e.preventDefault();controls[0]?.focus();}}
 if(comparison)return <Comparison capture={comparison.capture} primarySession={comparison.session} sourceFilter={comparison.sourceFilter} collector={liveRef.current} retainedSessions={liveSessions} sources={sources} collectorEpoch={collectorEpoch} onExit={exitComparison}/>;
 return <><input inert={modalOpen||!!sheet} ref={inputRef} className="sr-only" type="file" multiple accept=".ndjson,.jsonl,.json,.txt" aria-label="Choose NDJSON files" onChange={e=>{readFiles(e.target.files);e.target.value='';}}/>
 {screen==='import'||!session?<main className="import-page" inert={!!sheet}><header><div className="wordmark">↔ Network Log Lab</div><h1>See the whole conversation.</h1><p>Explore HTTP requests and the handoffs between your app and SDK. File imports stay in this browser. Live captures come from your paired local collector. URLs in a log are never contacted.</p>{session&&<button onClick={()=>setScreen('workspace')}>Back to workspace →</button>}</header>
 {liveControls}{sourceControls}<div className="drop-zone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();readFiles(e.dataTransfer.files);}}><div className="drop-symbol">⇣</div><h2>Drop NDJSON files here</h2><p>One JSON event per line · multiple sessions per file · schema 1.3</p><button className="primary" disabled={busy} onClick={()=>inputRef.current.click()}>Choose files…</button><p className="muted">16 MiB per file · 64 MiB combined · 100,000 events</p></div>
 <div className="sample-card"><div><strong>Start with a sample</strong><p>Current capture contract fixtures illustrate HTTP and handler flows.</p></div><select aria-label="Sample scenario" value={sample} onChange={e=>setSample(e.target.value)}>{sampleOptions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><button disabled={busy} onClick={()=>openSample()}>Open sample</button><button disabled={busy} onClick={()=>openSample(true)}>Open malformed sample</button></div>
 {busy&&<p role="status">Validating and reconstructing capture…</p>}{error&&<p role="alert" className="notice error">{error}</p>}
 {capture&&<><section className="import-result"><h2>Import results <span className="badge">{capture.events.length} events · {capture.sessions.length} sessions</span></h2>{capture.files.map(f=><p key={f.id}><strong>{f.name}</strong> · {(f.bytes/1024).toFixed(1)} KiB · {f.lines} lines · {f.events} accepted events</p>)}<h3>Import diagnostics · {capture.diagnostics.length}</h3><p className="muted">Invalid JSON/schema lines are skipped. Cross-event contradictions remain inspectable with diagnostics. Missing ends are incomplete observations, never inferred failures.</p>{!capture.diagnostics.length?<p className="success-text">✓ No validation issues</p>:<ol className="diagnostics">{capture.diagnostics.map((d,i)=><li key={i}><b className={d.severity}>{d.severity}</b> {d.fileName?`${d.fileName}${d.line?` · line ${d.line}`:''}: `:''}{d.message}</li>)}</ol>}</section><section><h2>Sessions ({capture.sessions.length})</h2>{capture.sessions.map(s=><div key={s.id} className="import-session"><div><h3>{s.name}</h3><p className="mono">{s.namespace} / {s.sessionId}</p><Summary session={s}/><p className="muted">{s.recordings.map((r,i)=>`Recording ${i+1}: schema ${r.schemaVersion} · ${r.producer?.platform??'platform not recorded'} · ${r.start?.data.id_source??'ID source not recorded'}`).join(' | ')}</p></div><button onClick={()=>changeSession(s.id)}>Open</button></div>)}</section></>}
 <footer>Local files, explicit attribution, observed facts. Refreshing clears imported data.</footer></main>:<div className="workspace" inert={!!sheet} ref={workspaceRef} style={{'--inspector-width':`${inspectorWidth}px`}}>
 <header className="topbar" inert={modalOpen}><button aria-label="Toggle session navigator" aria-expanded={navigatorOpen} onClick={()=>setNavigatorOpen(!navigatorOpen)}>☰</button><strong>↔ Network Log Lab</strong><span className="file-name">{capture.files.map(f=>f.name).join(', ')}</span><button onClick={()=>setScreen('import')}>{capture.diagnostics.length} diagnostics</button><span className="local-badge">● Processed locally</span><button onClick={()=>setScreen('import')}>Import…</button></header>
 <header className="mobile-bar" inert={modalOpen}><button onClick={()=>openSheet('sessions')}><strong>{session.name}</strong><small>{projection.exchanges.length} of {session.exchanges.length} requests · {session.handlers?.length??0} handlers ▾</small></button><button onClick={enterComparison}>Compare with…</button><button aria-label="Search" aria-pressed={mobileSearch} onClick={()=>setMobileSearch(!mobileSearch)}>⌕</button><button onClick={()=>openSheet('filters')}>Filters{projection.filtersActive?' •':''}</button></header>
 {mobileSearch&&<div className="mobile-search" inert={modalOpen}><input aria-label="Mobile search" type="search" placeholder="Search paths and components…" value={filters.search} onChange={e=>setFilter('search',e.target.value)}/></div>}
 {liveControls}{error&&<p role="alert" className="notice error">{error}</p>}<div className="workspace-body">{navigatorOpen&&<nav inert={modalOpen} className="session-nav" aria-label="Sessions">{sessionControls}</nav>}<main className="workspace-main" inert={modalOpen}><div className="toolbar"><div className="session-title"><h1>{session.name}</h1><button onClick={enterComparison}>Compare with…</button><span className="muted">{session.recordings[0]?.producer?.platform??'Platform not recorded'} · {session.origins.length} server origins · {session.recordings.length} recording(s)</span></div><div className="filter-controls">{filterControls}</div></div><div className="view-controls"><Segments label="View" value={view} choices={[["sequence","Sequence"],["list","List"]]} onChange={setView}/><span aria-live="polite">{projection.exchanges.length} of {session.exchanges.length} requests · {projection.handlers.length} of {session.handlers?.length??0} handler calls</span><button onClick={exportDiagram} disabled={!projection.visibleIds.size} title="Download the full current sequence, including offscreen rows">Download SVG</button><button className="collapse-all" onClick={()=>setCollapsed(collapsed.size?new Set():new Set(session.operations.map(o=>o.id)))}>{collapsed.size?'Expand':'Collapse'} all methods</button></div>
 {exportError&&<p role="alert" className="notice error">{exportError}</p>}
 {session.invalid&&<div className="notice">This session has contradictory records. Inspect diagnostics before drawing conclusions. <button onClick={()=>setScreen('import')}>View diagnostics</button></div>}
 {projection.visibleIds.size===0&&<div className="empty"><h2>No exchanges match</h2><p>Nothing matches the current search and filters.</p><button onClick={()=>setFilters(defaults)}>Clear search and filters</button></div>}
 <div className="diagram-host" hidden={view!=='sequence'}><Sequence exportRef={sequenceRef} session={session} filters={filters} collapsed={collapsed} expandedOwners={expanded[session.id]||new Set()} selectedId={selectedId} onSelect={select} onToggleCollapse={toggleCollapse} onToggleOwner={owner=>setExpanded(old=>{const next=new Set(old[session.id]||[]);next.has(owner)?next.delete(owner):next.add(owner);return {...old,[session.id]:next};})} onClose={closeInspector} onToggleHttpOnly={()=>setFilter('kind',filters.kind==='http'?'all':'http')}/></div>
 {view==='list'&&<div className="chronological-list">{listItems.slice(page*200,(page+1)*200).map(x=><button key={x.id} className={`list-row ${selectedId===x.id?'active':''}`} onClick={()=>select(x.id)}><strong>{x.kind==='http'?`${x.method} ${x.path}`:`↦ ${x.method||x.name}${x.isHandler?' · handler':''}`}</strong><span>{x.kind==='http'?x.origin:x.component} · {ownerLabel(x.owner)}</span><Badge item={x}/><span>{x.status?`HTTP ${x.status} · `:''}{duration(x.durationNs)}</span></button>)}{listItems.length>200&&<div className="actions"><button disabled={!page} onClick={()=>setPage(page-1)}>Previous</button><span>Page {page+1} of {Math.ceil(listItems.length/200)}</span><button disabled={(page+1)*200>=listItems.length} onClick={()=>setPage(page+1)}>Next</button></div>}</div>}
 <footer className="diagram-note">Event order, compressed spacing; not a duration scale. Pan sideways for more origins. ↑↓ select · Enter inspect · Esc close</footer></main>
 {item&&inspectorOpen&&<><div className="resize-handle" role="separator" aria-label="Resize inspector" aria-orientation="vertical" aria-valuemin={320} aria-valuemax={680} aria-valuenow={inspectorWidth} tabIndex={0} onKeyDown={e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();setInspectorWidth(w=>Math.max(320,Math.min(680,w+(e.key==='ArrowLeft'?20:-20))));}}} onPointerDown={e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(e.currentTarget.hasPointerCapture(e.pointerId))setInspectorWidth(Math.max(320,Math.min(680,window.innerWidth-e.clientX)));}}/><aside ref={inspectorRef} className="inspector-wrap" role={overlay?'dialog':undefined} aria-modal={overlay?true:undefined} aria-label={overlay?'Request and invocation details':undefined} onKeyDown={overlay?trapTab:undefined}><Inspector key={item.id} item={item} session={session} onSelect={select} onClose={closeInspector} hasPrior={history.length>0} onPrior={()=>{setSelectedId(history.at(-1));setHistory(history.slice(0,-1));}} onToggleCollapse={toggleCollapse} collapsed={collapsed.has(item.id)}/></aside></>}
 </div></div>}
 {sheet&&<div className="sheet-backdrop" onClick={()=>closeSheet()}><section ref={sheetRef} className="sheet" role="dialog" aria-modal="true" aria-label={sheet==='sessions'?'Choose session':'Filters'} onClick={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==='Tab'){const controls=[...e.currentTarget.querySelectorAll('button,input,select')].filter(x=>!x.disabled);const i=controls.indexOf(document.activeElement);if(e.shiftKey&&i===0){e.preventDefault();controls.at(-1)?.focus();}else if(!e.shiftKey&&i===controls.length-1){e.preventDefault();controls[0]?.focus();}}}}><button className="sheet-close" onClick={()=>closeSheet()}>Done</button>{sheet==='sessions'?<>{sessionControls}<button onClick={()=>{closeSheet();setScreen('import');}}>Import files</button></>:<div className="filter-controls">{filterControls}</div>}</section></div>}
 </>;
}
export default App;
