import React, { useState } from 'react';
import { actorLabel, ownerLabel, duration, statusInfo } from './ui.mjs';
const shown = value => value == null ? 'Not recorded' : typeof value==='object'?JSON.stringify(value):String(value);
export function Badge({item}) {const [kind,glyph,label]=statusInfo(item);return <span className={`badge ${kind}`}>{glyph} {label}</span>;}
function Copy({text,label='Copy'}) {
 const [state,setState]=useState('');
 return <button className="small" onClick={async()=>{try{await navigator.clipboard.writeText(text);setState('Copied');}catch{setState('Copy unavailable');}}}>{state||label}</button>;
}
function Fields({items,copy=false}) {return <dl>{items.map(([key,value])=><React.Fragment key={key}><dt>{key}</dt><dd>{shown(value)}{copy&&value!=null&&<Copy text={shown(value)} />}</dd></React.Fragment>)}</dl>;}
function Headers({title,headers}) {return <section><h3>{title} <span>{headers?`${headers.availability} · ${headers.entries.length} entries`:'Not recorded'}</span></h3>{headers?<><p className="muted">{headers.representation} representation · order {headers.order_preserved?'preserved':'not preserved'}{headers.reason?` · ${headers.reason}`:''}</p><table><tbody>{headers.entries.map((h,i)=><tr key={i}><th>{h.name}</th><td className={h.redacted?'sensitive':''}>{h.value}{h.redacted?' · redacted':''}</td></tr>)}</tbody></table>{!headers.entries.length&&<p className="muted">{headers.availability==='captured'?'No headers captured':`Headers ${headers.availability}`}</p>}</>:<p className="muted">Not recorded</p>}</section>;}
function Body({title,body}) {
 const [expanded,setExpanded]=useState(false),[pretty,setPretty]=useState(true);
 const raw=body?.content?.data;
 let parsed=null; if(raw!=null&&body.content.encoding==='utf-8'){try{parsed=JSON.stringify(JSON.parse(raw),null,2);}catch{}}
 const text=pretty&&parsed!==null?parsed:raw;
 const partial=body?.reason?.includes('partial')||body?.reason?.includes('read_failure')||(body?.total_bytes!=null&&body?.observed_bytes!=null&&body.observed_bytes<body.total_bytes);
 return <section className="payload"><h3>{title} <span>{!body?'Not recorded':`${body.availability}${body.redacted?' · Redacted':''}${body.truncated?' · Truncated':''}${partial?' · Partial':''}`}</span></h3>{body&&<><p className="muted">{body.stored_bytes} B stored · {body.observed_bytes??'unknown'} B observed · {body.total_bytes??'unknown'} B total</p><p className="muted">{body.representation} · {body.media_type??'media type not recorded'} · {body.content?.encoding??'no content'}{body.charset?` · ${body.charset}`:''}{body.content_encoding?` · ${body.content_encoding}`:''}</p>{body.reason&&<p className="notice">{body.reason}</p>}{body.redacted&&<p className="notice">Values were redacted before logging. Originals are not in this file.</p>}{body.truncated&&<p className="notice">The capture is truncated. Missing bytes cannot be recovered here.</p>}{partial&&<p className="notice">Only part of the transfer was observed. Stored bytes and transfer bytes describe different measurements.</p>}</>}{raw!=null?<><div className="actions">{parsed!==null&&<button onClick={()=>setPretty(!pretty)}>{pretty?'Raw':'Pretty'}</button>}<Copy text={raw}/><button aria-expanded={expanded} onClick={()=>setExpanded(!expanded)}>{expanded?'Collapse':'Expand'}</button></div><pre>{expanded?text:text.slice(0,160)+(text.length>160?'…':'')}</pre></>:<p className="muted">{body?.availability==='not_applicable'?'Not applicable':body?.availability==='unavailable'?'Unavailable':'Not recorded'}</p>}</section>;
}
function UrlDetails({request}) {
 let url;try{url=new URL(request?.url);}catch{}
 return <><section><h3>URL {request?.url&&<Copy text={request.url} label="Copy URL"/>}</h3><pre>{request?`${request.method} ${request.url}`:'Request start not recorded'}</pre>{url&&<Fields items={[
 ['Origin',url.origin],['Host',url.hostname],['Port',url.port||(url.protocol==='https:'?'443 (default)':'80 (default)')],['Path',url.pathname],['URL redacted',request.url_redacted],['Method source',request.method_source],['Configured method',request.configured_method],['Request target',request.request_target]
 ]}/>}</section><section><h3>Query parameters <span>{url?.search?'':'none'}</span></h3><table><tbody>{url&&[...url.searchParams].map(([k,v],i)=><tr key={i}><th>{k}</th><td>{v}</td></tr>)}</tbody></table></section></>;
}
export default function Inspector({item,session,onSelect,onClose,onPrior,hasPrior,onToggleCollapse,collapsed}) {
 const isHttp=!!item.rawEvents?.some(e=>e.event_type.startsWith('http.'));
 const awaited=item.invocation?.dispatch==='awaited';
 const tabs=isHttp?['Request','Response','Timing','Attribution','Raw events']:['Invocation','Timing','Attribution','Outcome','Children','Raw events'];
 const [tab,setTab]=useState(tabs[0]);
 const all=[...session.operations,...session.exchanges],parent=item.parentScope==='local'?all.find(x=>x.id===item.parentId&&x.recordingId===item.recordingId):null;
 const children=all.filter(x=>x.parentScope==='local'&&x.parentId===item.id&&x.recordingId===item.recordingId).sort((a,b)=>(a.start?.sequence??0)-(b.start?.sequence??0));
 const response=item.response,ended=item.end?.data,context=(item.start||item.rawEvents[0])?.context;
 const title=isHttp?`${item.method??'HTTP'} ${item.path??'Request start not recorded'}`:`${item.method||item.name}${item.isHandler?' · handler':''}`;
 const mainDuration=item.isHandler&&(!item.completion||item.completion==='observation_stopped')?null:item.durationNs;
 return <div className="inspector" role="region" aria-label="Details inspector">
 <header className="inspector-head"><div className="actions"><button onClick={onClose} aria-label="Close inspector">← Back</button>{hasPrior&&<button onClick={onPrior}>← prior</button>}</div><h2>{title}</h2><p className="muted">{isHttp?`${item.origin||'Origin not recorded'} · ${ownerLabel(item.owner)}`:actorLabel(item.origin)}</p><div className="status-row"><Badge item={item}/>{isHttp&&<span className="mono">{item.status?`HTTP ${item.status}${response?.status_text?' '+response.status_text:''}`:'No HTTP status recorded'}</span>}<span>{duration(mainDuration)}{!isHttp?' elapsed':''}</span></div>{item.isHandler&&<p className="muted">handler · {item.invocation?.dispatch||'dispatch not recorded'} · elapsed includes nested HTTP and waiting</p>}</header>
 {isHttp&&item.status>=200&&item.status<400&&['timeout','transport_error'].includes(item.outcome)&&<p className="notice">HTTP {item.status} headers were received, then the transfer failed. Header arrival is not completion.</p>}
 {item.isHandler&&item.completion==='threw'&&<p className="notice">{awaited?'The awaited handler rejected for':'The exception unwound to'} {actorLabel(item.invocation?.caller)}. {parent?`The caller's own outcome is ${parent.outcome}.`:'Caller completion was not recorded.'}</p>}
 {item.isHandler&&(!item.end||item.completion==='observation_stopped')&&<p className="notice">{awaited?'The handler settlement was not observed.':'The handler exit was not observed.'} No return or caller resumption is inferred.</p>}
 <div role="tablist" aria-label="Inspector views" className="tabs">{tabs.map(t=><button role="tab" key={t} aria-selected={tab===t} onClick={()=>setTab(t)}>{t}</button>)}</div>
 <div className="inspector-content" role="tabpanel" aria-label={tab}>
 {tab==='Request'&&<><UrlDetails request={item.request}/><Headers title="Request headers" headers={item.request?.headers}/><Body title="Request body" body={item.requestBody}/></>}
 {tab==='Response'&&<><section><h3>Response</h3><Fields items={[
 ['Status',item.status?`HTTP ${item.status}${response?.status_text?' '+response.status_text:''}`:'No status recorded'],['Headers observed',item.responseEvent?.timestamp],['Effective URL',response?.url],['Terminal outcome',item.outcome],['Application outcome',ended?.application_outcome],['End reason',ended?.end_reason],['Error',ended?.error===null?'None (error: null)':ended?.error]
 ]}/></section>{item.rawEvents.filter(e=>e.event_type==='http.response.headers').map(e=><Headers key={e.event_id} title={`${e.data.phase} response headers · ${e.data.response.status_code}`} headers={e.data.response.headers}/>)}<Body title="Response body" body={item.responseBody}/>{item.trailers?.map((e,i)=><Headers key={i} title={`Trailers · ${e.data?.direction||e.direction||''}`} headers={e.data?.headers||e.headers}/>)}</>}
 {tab==='Invocation'&&<><p>{awaited?'Awaited handler invocation. Promise settlement does not indicate that a business result was accepted. Other JavaScript can run while the caller awaits.':'Local method invocation. Method exit does not indicate that a business result was accepted.'}</p><Fields items={[
 ['Callee',actorLabel(item.origin)],['Caller',item.invocation?actorLabel(item.invocation.caller):'Not recorded (generic method)'],['Caller instrumentation',parent?'Instrumented':'Not resolved · label only'],['Kind',item.isHandler?'handler':'method'],['Dispatch',item.invocation?.dispatch],['Arguments','Not captured'],['Return value','Not captured'],['Business result','Not captured']
 ]}/>{parent&&<button onClick={()=>onSelect(parent.id)}>Open caller · {parent.method||parent.name}</button>}</>}
 {tab==='Timing'&&<><section><h3>Observed timing</h3><Fields items={[
 ['Started',item.start?.timestamp??'Not observed'],['Start monotonic ns',item.start?.monotonic_ns],['Start sequence',item.start?.sequence],...(isHttp?[['Response headers',item.responseEvent?.timestamp],['Time to headers',duration(item.timeToHeadersNs)]]:[]),['Ended',item.end?.timestamp??'Not observed'],['End monotonic ns',item.end?.monotonic_ns],['End sequence',item.end?.sequence],['Duration',duration(mainDuration)],['Recorded interval ns',item.end?.data.duration_ns],['Recording',item.recordingId],['Schema',item.start?.schema_version??item.rawEvents[0]?.schema_version]
 ]}/>{item.isHandler&&parent&&<p>{item.completion==='observation_stopped'?'Waiting observed until capture stopped':item.end?item.invocation?.dispatch==='awaited'?'Caller awaited handler settlement; other JavaScript can run':'Caller waited for the observed synchronous invocation':'Caller waiting exit was not observed'}.</p>}<p className="notice">Order follows each recording's sequence. Durations use its monotonic clock. Wall clocks and monotonic origins are independent across recordings and devices.</p>{item.returnedEarly&&<p className="notice">{item.end?'The request completed after its parent method ended.':'The parent method ended while this request was still observed in flight.'} The causal parent is preserved; this is not a handler resumption.</p>}</section>{item.metrics?.map((m,i)=><section key={i}><h3>Native metrics {i+1}</h3><pre>{JSON.stringify(m.data||m,null,2)}</pre></section>)}</>}
 {tab==='Attribution'&&<><section><h3>Attribution</h3>{isHttp&&<Fields items={[
 ['Initiator',actorLabel(item.initiator)],['Executor',actorLabel(item.executor)],['Adapter',item.start?.data.adapter],['Callsite',item.start?.data.origin?.callsite],['Attempt',item.attempt]
 ]}/>}<Fields copy items={[
 ['Trace ID',context?.trace_id],['Span ID',context?.span_id],['Parent span ID',context?.parent_span_id??'— (missing)'],['Parent scope',context?.parent_scope],['Session namespace',session.namespace],['Session ID',session.sessionId],['Recording ID',item.recordingId],['Start event ID',item.start?.event_id],['End event ID',item.end?.event_id]
 ]}/>{parent&&<button onClick={()=>onSelect(parent.id)}>{parent.isHandler?'Inside invocation':'Parent method'} · {parent.method||parent.name} → open</button>}{item.attempt?.previous_span_id&&<button onClick={()=>{const previous=all.find(x=>x.spanId===item.attempt.previous_span_id&&x.traceId===item.traceId);if(previous)onSelect(previous.id);}}>Open previous attempt</button>}<p className="muted">Trace IDs are available for future client/server correlation. Server logs are not merged in this version.</p></section></>}
 {tab==='Outcome'&&<><Fields items={[
 ['Completion',ended?.completion??'—'],['Outcome',ended?.outcome??'—'],['Error',ended?.error===null?'None (error: null)':ended?.error??'—'],['Stop reason',item.end?.extensions?.['capture.observation_stop_reason']??'—']
 ]}/>{ended?.error?.stage==='unknown'&&<p className="notice">stage=unknown is a method error stage, not a network classification.</p>}</>}
 {tab==='Children'&&<><p>{children.length} direct children, ordered by recorded sequence.</p>{children.map(child=><button className="child-row" key={child.id} onClick={()=>onSelect(child.id)}><strong>{child.request?`${child.method} ${child.path}`:`↦ ${child.name}`}</strong><span>{child.origin&&typeof child.origin==='string'?child.origin:ownerLabel(child.owner)}</span><Badge item={child}/>{child.request&&<small>Initiator: {actorLabel(child.initiator)} · Executor: {actorLabel(child.executor)}</small>}{child.returnedEarly&&<small>{child.end?'Completed after parent method ended':'Parent method ended before request completion was observed'}</small>}</button>)}<button onClick={()=>onToggleCollapse(item.id)}>{collapsed?'Expand':'Collapse'} child requests and calls</button></>}
 {tab==='Raw events'&&<><p className="muted">Recorded values are displayed as inert text. The viewer adds no redaction.</p><Copy text={item.rawSources?.map(s=>s.text).join('\n')||item.rawEvents.map(e=>JSON.stringify(e)).join('\n')} label="Copy recorded NDJSON"/>{item.rawEvents.map((e,i)=><section key={e.event_id}><h3>{e.event_type}</h3>{item.rawSources?.[i]&&<p className="muted">{item.rawSources[i].fileName} · line {item.rawSources[i].line}</p>}<pre>{item.rawSources?.[i]?.text||JSON.stringify(e)}</pre></section>)}</>}
 </div></div>;
}
