package dev.networklog.api

/** Application-owned instrumentation boundary. No Android, JSON, file, clock, or HTTP implementation. */
interface Logger {
    val enabled: Boolean
    fun startSession(name: String, sessionId: String? = null): Session
}
/** Opaque handle. Only the debug recorder understands the contents. */
interface CaptureContext {
    /** W3C context for a configured first-party destination; null when capture/propagation is disabled. */
    fun traceparent(destination: String): String? = null
}

data class Actor(val owner: String = "integrator", val component: String = "Customer", val method: String? = null)

class HeaderCapture private constructor(
    val entries: List<Pair<String, String>>, val availability: String, val reason: String?
) {
    companion object {
        fun partial(entries: List<Pair<String, String>>, reason: String = "caller_supplied_subset") = HeaderCapture(entries, "partial", reason)
        fun library(entries: List<Pair<String, String>>) = HeaderCapture(entries, "captured", null)
        fun unavailable(reason: String = "not_recorded") = HeaderCapture(emptyList(), "unavailable", reason)
    }
}
/** Construct inside a metadata supplier. Borrowed bytes are consumed synchronously by the debug adapter. */
class BodyCapture private constructor(
    val data: ByteArray?, val mediaType: String?, val complete: Boolean,
    val observedBytes: Long?, val totalBytes: Long?, val reason: String?, val absent: Boolean
) {
    companion object {
        fun bytes(data: ByteArray, mediaType: String = "application/json") = BodyCapture(data, mediaType, true, data.size.toLong(), data.size.toLong(), null, false)
        fun prefix(data: ByteArray, observedBytes: Long = data.size.toLong(), totalBytes: Long? = null,
                   reason: String = "incomplete_transfer", mediaType: String = "application/json") =
            BodyCapture(data, mediaType, false, observedBytes, totalBytes, reason, false)
        fun unavailable(reason: String = "not_recorded") = BodyCapture(null, null, false, null, null, reason, false)
        fun none(reason: String = "no_body") = BodyCapture(null, null, true, 0, 0, reason, true)
    }
}

interface Session {
    /** Empty when disabled and no external session ID was supplied. No IDs or clocks are generated by the no-op. */
    val sessionId: String
    fun startOperation(name: String, actor: Actor = Actor(), parent: CaptureContext? = null): Operation
    fun startHandler(name: String, caller: Actor, handler: Actor, parent: CaptureContext? = null): HandlerCall
    /** This executes application code, even when recording is disabled. Never mark it side-effect-free for R8. */
    fun <T> invokeHandler(name: String, caller: Actor, handler: Actor, parent: CaptureContext? = null, block: (CaptureContext) -> T): T {
        val call = startHandler(name, caller, handler, parent)
        try { return block(call.context).also { call.returned() } }
        catch (error: java.util.concurrent.CancellationException) { call.cancelled(error); throw error }
        catch (error: Throwable) { call.threw(error); throw error }
    }
    fun startRequest(method: String, url: String, parent: CaptureContext? = null,
        initiator: Actor = Actor(), executor: Actor = initiator,
        headers: () -> HeaderCapture = { HeaderCapture.unavailable() }, adapter: String = "customer.manual",
        retryOf: Exchange? = null, attemptReason: String = "retry"): Exchange
    fun end()
}
interface Operation {
    val context: CaptureContext
    fun complete(outcome: String = "success", error: Throwable? = null)
}
interface HandlerCall {
    val context: CaptureContext
    fun returned()
    fun threw(error: Throwable)
    fun cancelled(error: Throwable? = null)
    fun stopObservation(reason: String = "observation_stopped")
}
interface Exchange {
    val context: CaptureContext
    fun receiveResponseHeaders(status: Int, headers: () -> HeaderCapture = { HeaderCapture.unavailable() }, effectiveUrl: String? = null)
    fun captureRequestBody(body: () -> BodyCapture)
    fun captureResponseBody(body: () -> BodyCapture)
    fun completeResponse(status: Int? = null, headers: () -> HeaderCapture = { HeaderCapture.unavailable() },
        body: (() -> BodyCapture)? = null, effectiveUrl: String? = null, intentionallyClosed: Boolean = false)
    fun fail(error: Throwable, stage: String = "unknown")
    fun timeout(error: Throwable, stage: String = "unknown")
    fun cancel(error: Throwable? = null)
    fun stopObservation(reason: String = "observation_stopped")
}

/** Singleton handles avoid per-request allocations and never evaluate metadata suppliers. */
object NoOpLogger : Logger {
    override val enabled = false
    override fun startSession(name: String, sessionId: String?): Session =
        if (sessionId == null) DisabledSession else DisabledSessionWithId(sessionId)
}
private object DisabledContext : CaptureContext
private open class DisabledSessionWithId(override val sessionId: String) : Session {
    override fun startOperation(name: String, actor: Actor, parent: CaptureContext?) = DisabledOperation
    override fun startHandler(name: String, caller: Actor, handler: Actor, parent: CaptureContext?) = DisabledHandler
    override fun startRequest(method: String, url: String, parent: CaptureContext?, initiator: Actor, executor: Actor,
                              headers: () -> HeaderCapture, adapter: String, retryOf: Exchange?, attemptReason: String) = DisabledExchange
    override fun end() = Unit
}
private object DisabledSession : DisabledSessionWithId("")
private object DisabledOperation : Operation {
    override val context = DisabledContext
    override fun complete(outcome: String, error: Throwable?) = Unit
}
private object DisabledHandler : HandlerCall {
    override val context = DisabledContext
    override fun returned() = Unit
    override fun threw(error: Throwable) = Unit
    override fun cancelled(error: Throwable?) = Unit
    override fun stopObservation(reason: String) = Unit
}
private object DisabledExchange : Exchange {
    override val context = DisabledContext
    override fun receiveResponseHeaders(status: Int, headers: () -> HeaderCapture, effectiveUrl: String?) = Unit
    override fun captureRequestBody(body: () -> BodyCapture) = Unit
    override fun captureResponseBody(body: () -> BodyCapture) = Unit
    override fun completeResponse(status: Int?, headers: () -> HeaderCapture, body: (() -> BodyCapture)?, effectiveUrl: String?, intentionallyClosed: Boolean) = Unit
    override fun fail(error: Throwable, stage: String) = Unit
    override fun timeout(error: Throwable, stage: String) = Unit
    override fun cancel(error: Throwable?) = Unit
    override fun stopObservation(reason: String) = Unit
}
